# Generated by Django 5.2.3 on 2025-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_org_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='role',
            field=models.TextField(default='admin', max_length=20),
        ),
    ]
