# Generated by Django 5.2.3 on 2025-06-23 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studentprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('phd', 'PhD'), ('vocational', 'Vocational/Trade School')], max_length=50)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('financial_need', models.CharField(choices=[('not_required', 'Not Required'), ('preferred', 'Preferred'), ('required', 'Required')], default='not_required', max_length=20)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('contact', models.EmailField(max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='scholarship_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(limit_choices_to={'role': 'sponsor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
