# Generated by Django 5.2.3 on 2025-06-25 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_scholarshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='scholarship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.scholarship'),
        ),
    ]
