# Generated by Django 5.2.3 on 2025-06-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_exam_scholarship'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
