# Generated by Django 5.2.3 on 2025-06-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_review_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(choices=[('money', 'Money Based'), ('materials', 'Study Materials'), ('books', 'Books'), ('uniform', 'Uniform/Dress'), ('mixed', 'Mixed Support')], default='money', max_length=50),
        ),
    ]
