from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('studreg',views.studreg, name='studreg'),
    path('login_view',views.login_view,name='login_view'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('sponreg',views.sponreg,name='sponreg'),
    path('about',views.about,name='about'),
    path('ourscholar',views.ourscholar,name='ourscholar'),
    path('addscholar',views.addscholar,name='addscholar'),
    path('allscholar',views.allscholar,name='allscholar'),
    path('studlist',views.studlist,name='studlist'),
    path('studdetails/<int:student_id>/', views.studdetails, name='studdetails'),
    path('delete_student/<int:pk>/', views.delete_student, name='delete_student'),
    path('sponlist',views.sponlist, name='sponlist'),
    path('delete-sponsor/<int:sponsor_id>/', views.delete_sponsor, name='delete_sponsor'),
    path('spondetail/<int:sponsor_id>/',views.spondetail,name='spondetail'),
    path('examadmin',views.examadmin,name='examadmin'),
    path('delete_exam/<int:exam_id>/', views.delete_exam, name='delete_exam'),
    path('exam/<int:exam_id>/',views.exam,name='exam'),
    path('registered_scholarships/', views.registered_scholarships, name='registered_scholarships'),
    path('attend-exam/<int:scholarship_id>/', views.attend_exam, name='attend_exam'),
    path('apply/<int:scholarship_id>/', views.apply_scholarship, name='apply_scholarship'),
    path('registered_scholarships/', views.registered_scholarships, name='registered_scholarships'),
    path('my-sponsors/', views.my_sponsors, name='my_sponsors'),
    path('applicants/', views.applicants_list, name='applicants_list'),
    path('reviews/', views.review_page, name='review_page'),
    path('reviews/delete/<int:review_id>/', views.delete_review, name='delete_review'),
]